### ISSUE TITLE
Remove unnecessary unicode characters in goal JSON

### ISSUE THREAD

**Issue by jpeterson** [UNStats/CountryProfiles#11]
There are some goal JSON files which have unnecessary unicode characters.

Some examples:

https://github.com/UNStats/FIS4SDGs_New/search?q=%22u00e2%22+language%3AJSON&unscoped_q=%22u00e2%22+language%3AJSON

![image](https://user-images.githubusercontent.com/3399064/60607941-80442a80-9d7b-11e9-8a7a-4cf75c66e8e0.png)

**Comment by gonzalezmorales** [comment]
@jpeterson :

The em-dash character was being encoded as "\u00e2\u20ac\u201c", which apparently is not unicode.  The correct unicode is \u2014.   I've changed this, please see if it renders properly.  Otherwise I'll replace with colon.  

see new json files in https://github.com/UNStats/FIS4SDGs_New/tree/master/data/unsd/countryProfiles/output

**Comment by jpeterson** [comment]
Resolved by latest JSON files from @gonzalezmorales (added in #30).
