### ISSUE TITLE
Styling of headline indicators

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/CountryProfiles#35]
(1) Collapsible accordion
Explore some functionality to show/hide the contents of the 4 tabs ("headline indicators")

(2) Table styling
maybe add some styling to the table (stripped table to aid readability, less space between rows, reduced maximum width...)

![image](https://user-images.githubusercontent.com/7047819/60849957-25676480-a1bb-11e9-9927-772c7b0d3012.png)

**Comment by gonzalezmorales** [comment]
@codylawson - 
I've marked this as high priority because it's important for some users I've talked to (as well as a bit of mobile responsiveness)... however it can happen later in the week

**Comment by gonzalezmorales** [comment]
Just as an example... maybe something like this, with only one panel expanded at a time...

![image](https://user-images.githubusercontent.com/7047819/60850422-46c95000-a1bd-11e9-9d56-429029f6f91b.png)

**Comment by gonzalezmorales** [comment]
Some additional ideas...
Note: if the country name is put next to the app title, then in this case "Country Profile: xxx" should be in singular (not plural)

![image](https://user-images.githubusercontent.com/7047819/60851398-05d33a80-a1c1-11e9-814f-97901f1a993a.png)

**Comment by codylawson** [comment]
@gonzalezmorales Here is the updated country header using accordion instead of tabs. Also includes the country name in the top nav header, and the header now sticky scrolls.

![Screen Shot 2019-07-12 at 12 05 19 PM](https://user-images.githubusercontent.com/5149922/61149026-630b0c80-a49d-11e9-80b8-0473af02abb4.png)
![Screen Shot 2019-07-12 at 12 05 22 PM](https://user-images.githubusercontent.com/5149922/61149027-630b0c80-a49d-11e9-9f56-cf8e9b209228.png)
![Screen Shot 2019-07-12 at 12 05 33 PM](https://user-images.githubusercontent.com/5149922/61149028-630b0c80-a49d-11e9-80e3-5a4bc4a2d9b2.png)

**Comment by gonzalezmorales** [comment]
@codylawson - I like it. thanks

**Comment by gonzalezmorales** [comment]
@codylawson - is it possible to hide the 'dashboard', 'csv download' and 'view data' icons in the mobile version? nobody will be looking at this functionality from a cell phone... I think

**Comment by codylawson** [comment]
@gonzalezmorales Sure, I'll update the branch.

**Comment by codylawson** [comment]
Resolved in #41
